### ISSUE TITLE
Same Sized bundles aren't same size

### ISSUE THREAD

**Issue by hanford** [Southpaw17/webpack-compare#1]
Thanks for building this plugin! I'm finding it super useful and have integrated it into my companies CI server so we're using this a lot now!

I've noticed a bug where we're getting bundles that are not the same size, showing up in Same Sized bundles .. any ideas?

![](http://d.pr/i/HkesFi+)

**Comment by Southpaw17** [comment]
This is actually by design, depending on your webpack configurations or a few other factors, there can be small fluctuations in bundle size even when the contents of that bundle are unchanged.  This can cause the Larger / Smaller Bundle lists to be polluted with a lot of noise.

As a result, "Same Sized Bundles" actually contains bundles which are within a small percent of their previous version.  For example, you have a bundle at the bottom there which changed by a measly 0.34% while your app.js changed by only a few bytes.  Unless you're *really* aiming for some serious optimizations, these are probably totally inconsequential.

However, I should probably make this "same sized threshold" configurable and rename it to "similarly sized" or something along those lines to make this clearer.

**Comment by hanford** [comment]
Awesome! Thanks you!
